# Generated by Django 2.2.4 on 2019-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('normbalance', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Account Types',
            },
        ),
    ]
