# Generated by Django 2.2.4 on 2019-09-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttypes',
            name='category',
        ),
    ]
