# Generated by Django 2.2.4 on 2019-09-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_accounttypes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttypes',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
