# Generated by Django 2.2.4 on 2019-09-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accounttypes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttypes',
            name='category',
        ),
    ]
