# Generated by Django 2.2.4 on 2019-09-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account',
            field=models.IntegerField(unique=True),
        ),
    ]
