# Generated by Django 2.2.4 on 2019-09-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='number',
            field=models.IntegerField(default=1, null=True, unique=True),
        ),
    ]
