# Generated by Django 2.2.4 on 2019-09-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190901_1958'),
        ('products', '0003_mfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('MFPs', models.ManyToManyField(to='products.MFP')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
